### ISSUE TITLE
Make solver able to solve what returned by mem[...]

### ISSUE THREAD

**Issue by antoniobianchi333** [angr/claripy#160]
As discussed on Slack, state.mem returns "something" that you cannot use with state.solver.
Example:
```
In [23]: a.mem[a.regs.rcx+40].int
Out[23]: <int (32 bits) <BV32 0xfc18eda3> at 0xc0000fef
In [24]: a.memory.load(a.regs.rcx+40,size=4)
Out[24]: <BV32 0xa3ed18fc>
```
but
```
In [21]: hex(a.solver.eval_one(a.memory.load(a.regs.rcx+40,size=4)))
Out[21]: '0xa3ed18fc'
In [22]: hex(a.solver.eval_one(a.mem[a.regs.rcx+40].int))
...

~/angr-dev/angr/angr/state_plugins/view.py in __getattr__(self, k)
    206         if k in SimMemView.types:
    207             return self._deeper(ty=SimMemView.types[k].with_arch(self.state.arch))
--> 208         raise AttributeError(k)
    209 
    210     def __setattr__(self, k, v):
AttributeError: cache_key

```

**Comment by rhelmot** [comment]
antonio. you're supposed to say `.resolved` on the memview object if you want to use it in a readable fashion

**Comment by zardus** [comment]
We could probably do this automatically in the SimSolver plug-in, though,
couldn’t we?

**Comment by rhelmot** [comment]
the only other type we do that for is SimActionObjects and native python ints/floats and that makes sense because you can sort of use those objects in every way that you can use ASTs i.e. doing arithmetic with them, but you can't do that with memviews! They are explicitly meant to not hold those semantics until you hit `.resolved`, you can still manipulate their type and their address and in the case of complex types go deeper into their values.

Furthermore there's already sugar for the usecase of directly evaluating the AST that comes out of a memview. You can just say `.concrete` instead of `.resolved`.
